name: proyecto_pubsub
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  
  #FIREBASE 
  firebase_auth: ^2.0.0
  cloud_firestore: ^1.0.3
  #UTILS
  get: ^4.0.0-nullsafety.0
  fluttertoast: ^8.0.9
  mailer: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0



# The following section is specific to Flutter.
flutter:


  uses-material-design: true
